### PR TITLE
Added highlight & strike through to checked todos

### PR DESCRIPTION
**Pull request by tab21**
This is my solution to #1.
I have added **greenyellow Highlight** and strike through to every that is _checked Todo_.

Screenshot from 2022-10-09 15-24-47

### CODE REVIEW

**Review by nakshatraraghav — CHANGES_REQUESTED** [review]
Hi @tab21, amazing work, but can you make it so that the highlight and strike-through  also includes the category of the todo, also can you reduce opacity of the todo, when it is highlighted, thanks!

**Comment by tab21** [comment]
Hey I have done the changes requested.
Screenshot from 2022-10-09 16-21-05

**Comment by nakshatraraghav** [comment]
great work @tab21, pr accepted!

**Comment by tab21** [comment]
Thank you :)

**Pull request merged**
