### PR TITLE
feat: localStorage functionality

### PR DESCRIPTION
**Pull request by ThPadelis**
Add functionality to save todos in the localStorage

### CODE REVIEW

**Comment by ThPadelis** [comment]
Could you please add `hacktoberfest-accepted` label to my PR?

**Comment by nakshatraraghav** [comment]
> Could you please add `hacktoberfest-accepted` label to my PR?

hi @ThPadelis before i merge this pr and add the hacktoberfest-accepted label, could you add a working video/ screenshot of the feature you implemented, thanks!

**Comment by ThPadelis** [comment]
Sure thing!
todo-app

**Comment by nakshatraraghav** [comment]
thanks for contributing to this project @ThPadelis.

**Comment by nakshatraraghav** [comment]
hi @ThPadelis, there seems to be a issue, with this, it isnt working when the localStorage is not set initially
image
image
please fix this issue asap as other people are also working on this repository.

**Pull request merged**
